name: Generate Snake Animation

# Triggers
on:
  workflow_dispatch:    # Manual trigger
  schedule:
    - cron: '0 0 * * *' # Daily at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Ensure output folder exists
      - name: Create output folder
        run: mkdir -p output

      # Step 3: Generate Snake SVG
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: hrishi3466     # Replace with your GitHub username
          output: output/snake.svg         # Path to save SVG
          palette: github-dark             # Dark GitHub palette
          color_snake: '#00FF00'           # Snake color
          color_dots: '#00FF00, #00CC00, #009900, #006600, #003300' # Contribution dot colors
