name: Snake Animation

on:
  workflow_dispatch:    # manual trigger
  schedule:
    - cron: '0 0 * * *' # daily at midnight UTC

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v3

      # Generate the snake
      - name: Generate Snake SVG
        uses: mattdavis035/github-contribution-snake@main
        with:
          github_user: hrishi3466
          output: output/snake.svg
